INSERT INTO city
(
  name
)
VALUES
('ADANA'),
('ADIYAMAN'),
('AFYON'),
('AGRI'),
('AMASYA'),
('ANKARA'),
('ANTALYA'),
('ARTVIN'),
('AYDIN'),
('BALIKESIR'),
('BILECIK'),
('BINGOL'),
('BITLIS'),
('BOLU'),
('BURDUR'),
('BURSA'),
('CANAKKALE'),
('CANKIRI'),
('CORUM'),
('DENIZLI'),
('DIYARBAKIR'),
('EDIRNE'),
('ELAZIG'),
('ERZINCAN'),
('ERZURUM'),
('ESKISEHIR'),
('GAZIANTEP'),
('GIRESUN'),
('GUMUSHANE'),
('HAKKARI'),
('HATAY'),
('ISPARTA'),
('ICEL'),
('ISTANBUL'),
('IZMIR'),
('KARS'),
('KASTAMONU'),
('KAYSERI'),
('KIRKLARELI'),
('KIRSEHIR'),
('KOCAELI'),
('KONYA'),
('KUTAHYA'),
('MALATYA'),
('MANISA'),
('KAHRAMANMARAS'),
('MARDIN'),
('MUGLA'),
('MUS'),
('NEVSEHIR'),
('NIGDE'),
('ORDU'),
('RIZE'),
('SAKARYA'),
('SAMSUN'),
('SIIRT'),
('SINOP'),
('SIVAS'),
('TEKIRDAG'),
('TOKAT'),
('TRABZON'),
('TUNCELI'),
('SANLIURFA'),
('USAK'),
('VAN'),
('YOZGAT'),
('ZONGULDAK'),
('AKSARAY'),
('BAYBURT'),
('KARAMAN'),
('KIRIKKALE'),
('BATMAN'),
('SIRNAK'),
('BARTIN'),
('ARDAHAN'),
('IGDIR'),
('YALOVA'),
('KARABUK'),
('KILIS'),
('OSMANIYE'),
('DUZCE');

INSERT INTO district(name, city_id) VALUES
('ALADAG',1),
('CEYHAN',1),
('CUKUROVA',1),
('FEKE',1),
('IMAMOGLU',1),
('KARAISALI',1),
('KARATAS',1),
('KOZAN',1),
('POZANTI',1),
('SAIMBEYLI',1),
('SARICAM',1),
('SEYHAN',1),
('TUFANBEYLI',1),
('YUMURTALIK',1),
('YUREGIR',1);

INSERT INTO district(name, city_id) VALUES
('BESNI',2),
('CELIKHAN',2),
('GERGER',2),
('GOLBASI',2),
('KAHTA',2),
('MERKEZ',2),
('SAMSAT',2),
('SINCIK',2),
('TUT',2);

INSERT INTO district(name, city_id) VALUES
('BASMAKCI',3),
('BAYAT',3),
('BOLVADIN',3),
('CAY',3),
('COBANLAR',3),
('DAZKIRI',3),
('DINAR',3),
('EMIRDAG',3),
('EVCILER',3),
('HOCALAR',3),
('IHSANIYE',3),
('ISCEHISAR',3),
('KIZILOREN',3),
('MERKEZ',3),
('SANDIKLI',3),
('SINANPASA',3),
('SULTANDAGI',3),
('SUHUT',3);

INSERT INTO district(name, city_id) VALUES
('DIYADIN',4),
('DOGUBAYAZIT',4),
('ELESKIRT',4),
('HAMUR',4),
('MERKEZ',4),
('PATNOS',4),
('TASLICAY',4),
('TUTAK',4);

INSERT INTO district(name, city_id) VALUES
('AGACOREN',68),
('ESKIL',68),
('GULAGAC',68),
('GUZELYURT',68),
('MERKEZ',68),
('ORTAKOY',68),
('SARIYAHSI',68),
('SULTANHANI',68);

INSERT INTO district(name, city_id) VALUES
('GOYNUCEK',5),
('GUMUSHACIKOY',5),
('HAMAMOZU',5),
('MERKEZ',5),
('MERZIFON',5),
('SULUOVA',5),
('TASOVA',5);

INSERT INTO district(name, city_id) VALUES
('AKYURT',6),
('ALTINDAG',6),
('AYAS',6),
('BALA',6),
('BEYPAZARI',6),
('CAMLIDERE',6),
('CANKAYA',6),
('CUBUK',6),
('ELMADAG',6),
('ETIMESGUT',6),
('EVREN',6),
('GOLBASI',6),
('GUDUL',6),
('HAYMANA',6),
('KAHRAMANKAZAN',6),
('KALECIK',6),
('KECIOREN',6),
('KIZILCAHAMAM',6),
('MAMAK',6),
('NALLIHAN',6),
('POLATLI',6),
('PURSAKLAR',6),
('SINCAN',6),
('SEREFLIKOCHISAR',6),
('YENIMAHALLE',6);

INSERT INTO district(name, city_id) VALUES
('AKSEKI',7),
('AKSU',7),
('ALANYA',7),
('DEMRE',7),
('DOSEMEALTI',7),
('ELMALI',7),
('FINIKE',7),
('GAZIPASA',7),
('GUNDOGMUS',7),
('IBRADI',7),
('KAS',7),
('KEMER',7),
('KEPEZ',7),
('KONYAALTI',7),
('KORKUTELI',7),
('KUMLUCA',7),
('MANAVGAT',7),
('MURATPASA',7),
('SERIK',7);

INSERT INTO district(name, city_id) VALUES
('CILDIR',75),
('DAMAL',75),
('GOLE',75),
('HANAK',75),
('MERKEZ',75),
('POSOF',75);

INSERT INTO district(name, city_id) VALUES
('ARDANUC',8),
('ARHAVI',8),
('BORCKA',8),
('HOPA',8),
('KEMALPASA',8),
('MERKEZ',8),
('MURGUL',8),
('SAVSAT',8),
('YUSUFELI',8);

INSERT INTO district(name, city_id) VALUES
('BOZDOGAN',9),
('BUHARKENT',9),
('CINE',9),
('DIDIM',9),
('EFELER',9),
('GERMENCIK',9),
('INCIRLIOVA',9),
('KARACASU',9),
('KARPUZLU',9),
('KOCARLI',9),
('KOSK',9),
('KUSADASI',9),
('KUYUCAK',9),
('NAZILLI',9),
('SOKE',9),
('SULTANHISAR',9),
('YENIPAZAR',9);

INSERT INTO district(name, city_id) VALUES
('ALTIEYLUL',10),
('AYVALIK',10),
('BALYA',10),
('BANDIRMA',10),
('BIGADIC',10),
('BURHANIYE',10),
('DURSUNBEY',10),
('EDREMIT',10),
('ERDEK',10),
('GOMEC',10),
('GONEN',10),
('HAVRAN',10),
('IVRINDI',10),
('KARESI',10),
('KEPSUT',10),
('MANYAS',10),
('MARMARA',10),
('SAVASTEPE',10),
('SINDIRGI',10),
('SUSURLUK',10);

INSERT INTO district(name, city_id) VALUES
('AMASRA',74),
('KURUCASILE',74),
('MERKEZ',74),
('ULUS',74);

INSERT INTO district(name, city_id) VALUES
('BESIRI',72),
('GERCUS',72),
('HASANKEYF',72),
('KOZLUK',72),
('MERKEZ',72),
('SASON',72);

INSERT INTO district(name, city_id) VALUES
('AYDINTEPE',69),
('DEMIROZU',69),
('MERKEZ',69);

INSERT INTO district(name, city_id) VALUES
('BOZUYUK',11),
('GOLPAZARI',11),
('INHISAR',11),
('MERKEZ',11),
('OSMANELI',11),
('PAZARYERI',11),
('SOGUT',11),
('YENIPAZAR',11);

INSERT INTO district(name, city_id) VALUES
('ADAKLI',12),
('GENC',12),
('KARLIOVA',12),
('KIGI',12),
('MERKEZ',12),
('SOLHAN',12),
('YAYLADERE',12),
('YEDISU',12);

INSERT INTO district(name, city_id) VALUES
('ADILCEVAZ',13),
('AHLAT',13),
('GUROYMAK',13),
('HIZAN',13),
('MERKEZ',13),
('MUTKI',13),
('TATVAN',13);

INSERT INTO district(name, city_id) VALUES
('DORTDIVAN',14),
('GEREDE',14),
('GOYNUK',14),
('KIBRISCIK',14),
('MENGEN',14),
('MERKEZ',14),
('MUDURNU',14),
('SEBEN',14),
('YENICAGA',14);

INSERT INTO district(name, city_id) VALUES
('AGLASUN',15),
('ALTINYAYLA',15),
('BUCAK',15),
('CAVDIR',15),
('CELTIKCI',15),
('GOLHISAR',15),
('KARAMANLI',15),
('KEMER',15),
('MERKEZ',15),
('TEFENNI',15),
('YESILOVA',15);

INSERT INTO district(name, city_id) VALUES
('BUYUKORHAN',16),
('GEMLIK',16),
('GURSU',16),
('HARMANCIK',16),
('INEGOL',16),
('IZNIK',16),
('KARACABEY',16),
('KELES',16),
('KESTEL',16),
('MUDANYA',16),
('MUSTAFAKEMALPASA',16),
('NILUFER',16),
('ORHANELI',16),
('ORHANGAZI',16),
('OSMANGAZI',16),
('YENISEHIR',16),
('YILDIRIM',16);

INSERT INTO district(name, city_id) VALUES
('AYVACIK',17),
('BAYRAMIC',17),
('BIGA',17),
('BOZCAADA',17),
('CAN',17),
('ECEABAT',17),
('EZINE',17),
('GELIBOLU',17),
('GOKCEADA',17),
('LAPSEKI',17),
('MERKEZ',17),
('YENICE',17);

INSERT INTO district(name, city_id) VALUES
('ATKARACALAR',18),
('BAYRAMOREN',18),
('CERKES',18),
('ELDIVAN',18),
('ILGAZ',18),
('KIZILIRMAK',18),
('KORGUN',18),
('KURSUNLU',18),
('MERKEZ',18),
('ORTA',18),
('SABANOZU',18),
('YAPRAKLI',18);

INSERT INTO district(name, city_id) VALUES
('ALACA',19),
('BAYAT',19),
('BOGAZKALE',19),
('DODURGA',19),
('ISKILIP',19),
('KARGI',19),
('LACIN',19),
('MECITOZU',19),
('MERKEZ',19),
('OGUZLAR',19),
('ORTAKOY',19),
('OSMANCIK',19),
('SUNGURLU',19),
('UGURLUDAG',19);

INSERT INTO district(name, city_id) VALUES
('ACIPAYAM',20),
('BABADAG',20),
('BAKLAN',20),
('BEKILLI',20),
('BEYAGAC',20),
('BOZKURT',20),
('BULDAN',20),
('CAL',20),
('CAMELI',20),
('CARDAK',20),
('CIVRIL',20),
('GUNEY',20),
('HONAZ',20),
('KALE',20),
('MERKEZEFENDI',20),
('PAMUKKALE',20),
('SARAYKOY',20),
('SERINHISAR',20),
('TAVAS',20);

INSERT INTO district(name, city_id) VALUES
('BAGLAR',21),
('BISMIL',21),
('CERMIK',21),
('CINAR',21),
('CUNGUS',21),
('DICLE',21),
('EGIL',21),
('ERGANI',21),
('HANI',21),
('HAZRO',21),
('KAYAPINAR',21),
('KOCAKOY',21),
('KULP',21),
('LICE',21),
('SILVAN',21),
('SUR',21),
('YENISEHIR',21);

INSERT INTO district(name, city_id) VALUES
('AKCAKOCA',81),
('CUMAYERI',81),
('CILIMLI',81),
('GOLYAKA',81),
('GUMUSOVA',81),
('KAYNASLI',81),
('MERKEZ',81),
('YIGILCA',81);

INSERT INTO district(name, city_id) VALUES
('ENEZ',22),
('HAVSA',22),
('IPSALA',22),
('KESAN',22),
('LALAPASA',22),
('MERIC',22),
('MERKEZ',22),
('SULOGLU',22),
('UZUNKOPRU',22);

INSERT INTO district(name, city_id) VALUES
('AGIN',23),
('ALACAKAYA',23),
('ARICAK',23),
('BASKIL',23),
('KARAKOCAN',23),
('KEBAN',23),
('KOVANCILAR',23),
('MADEN',23),
('MERKEZ',23),
('PALU',23),
('SIVRICE',23);

INSERT INTO district(name, city_id) VALUES
('CAYIRLI',24),
('ILIC',24),
('KEMAH',24),
('KEMALIYE',24),
('MERKEZ',24),
('OTLUKBELI',24),
('REFAHIYE',24),
('TERCAN',24),
('UZUMLU',24);

INSERT INTO district(name, city_id) VALUES
('ASKALE',25),
('AZIZIYE',25),
('CAT',25),
('HINIS',25),
('HORASAN',25),
('ISPIR',25),
('KARACOBAN',25),
('KARAYAZI',25),
('KOPRUKOY',25),
('NARMAN',25),
('OLTU',25),
('OLUR',25),
('PALANDOKEN',25),
('PASINLER',25),
('PAZARYOLU',25),
('SENKAYA',25),
('TEKMAN',25),
('TORTUM',25),
('UZUNDERE',25),
('YAKUTIYE',25);

INSERT INTO district(name, city_id) VALUES
('ALPU',26),
('BEYLIKOVA',26),
('CIFTELER',26),
('GUNYUZU',26),
('HAN',26),
('INONU',26),
('MAHMUDIYE',26),
('MIHALGAZI',26),
('MIHALICCIK',26),
('ODUNPAZARI',26),
('SARICAKAYA',26),
('SEYITGAZI',26),
('SIVRIHISAR',26),
('TEPEBASI',26);

INSERT INTO district(name, city_id) VALUES
('ARABAN',27),
('ISLAHIYE',27),
('KARKAMIS',27),
('NIZIP',27),
('NURDAGI',27),
('OGUZELI',27),
('SAHINBEY',27),
('SEHITKAMIL',27),
('YAVUZELI',27);

INSERT INTO district(name, city_id) VALUES
('ALUCRA',28),
('BULANCAK',28),
('CAMOLUK',28),
('CANAKCI',28),
('DERELI',28),
('DOGANKENT',28),
('ESPIYE',28),
('EYNESIL',28),
('GORELE',28),
('GUCE',28),
('KESAP',28),
('MERKEZ',28),
('PIRAZIZ',28),
('SEBINKARAHISAR',28),
('TIREBOLU',28),
('YAGLIDERE',28);

INSERT INTO district(name, city_id) VALUES
('KELKIT',29),
('KOSE',29),
('KURTUN',29),
('MERKEZ',29),
('SIRAN',29),
('TORUL',29);

INSERT INTO district(name, city_id) VALUES
('CUKURCA',30),
('DERECIK',30),
('MERKEZ',30),
('SEMDINLI',30),
('YUKSEKOVA',30);

INSERT INTO district(name, city_id) VALUES
('ALTINOZU',31),
('ANTAKYA',31),
('ARSUZ',31),
('BELEN',31),
('DEFNE',31),
('DORTYOL',31),
('ERZIN',31),
('HASSA',31),
('ISKENDERUN',31),
('KIRIKHAN',31),
('KUMLU',31),
('PAYAS',31),
('REYHANLI',31),
('SAMANDAG',31),
('YAYLADAGI',31);

INSERT INTO district(name, city_id) VALUES
('ARALIK',76),
('KARAKOYUNLU',76),
('MERKEZ',76),
('TUZLUCA',76);

INSERT INTO district(name, city_id) VALUES
('AKSU',32),
('ATABEY',32),
('EGIRDIR',32),
('GELENDOST',32),
('GONEN',32),
('KECIBORLU',32),
('MERKEZ',32),
('SENIRKENT',32),
('SUTCULER',32),
('SARKIKARAAGAC',32),
('ULUBORLU',32),
('YALVAC',32),
('YENISARBADEMLI',32);

INSERT INTO district(name, city_id) VALUES
('ADALAR',34),
('ARNAVUTKOY',34),
('ATASEHIR',34),
('AVCILAR',34),
('BAGCILAR',34),
('BAHCELIEVLER',34),
('BAKIRKOY',34),
('BASAKSEHIR',34),
('BAYRAMPASA',34),
('BESIKTAS',34),
('BEYKOZ',34),
('BEYLIKDUZU',34),
('BEYOGLU',34),
('BUYUKCEKMECE',34),
('CATALCA',34),
('CEKMEKOY',34),
('ESENLER',34),
('ESENYURT',34),
('EYUPSULTAN',34),
('FATIH',34),
('GAZIOSMANPASA',34),
('GUNGOREN',34),
('KADIKOY',34),
('KAGITHANE',34),
('KARTAL',34),
('KUCUKCEKMECE',34),
('MALTEPE',34),
('PENDIK',34),
('SANCAKTEPE',34),
('SARIYER',34),
('SILIVRI',34),
('SULTANBEYLI',34),
('SULTANGAZI',34),
('SILE',34),
('SISLI',34),
('TUZLA',34),
('UMRANIYE',34),
('USKUDAR',34),
('ZEYTINBURNU',34);

INSERT INTO district(name, city_id) VALUES
('ALIAGA',35),
('BALCOVA',35),
('BAYINDIR',35),
('BAYRAKLI',35),
('BERGAMA',35),
('BEYDAG',35),
('BORNOVA',35),
('BUCA',35),
('CESME',35),
('CIGLI',35),
('DIKILI',35),
('FOCA',35),
('GAZIEMIR',35),
('GUZELBAHCE',35),
('KARABAGLAR',35),
('KARABURUN',35),
('KARSIYAKA',35),
('KEMALPASA',35),
('KINIK',35),
('KIRAZ',35),
('KONAK',35),
('MENDERES',35),
('MENEMEN',35),
('NARLIDERE',35),
('ODEMIS',35),
('SEFERIHISAR',35),
('SELCUK',35),
('TIRE',35),
('TORBALI',35),
('URLA',35);

INSERT INTO district(name, city_id) VALUES
('AFSIN',46),
('ANDIRIN',46),
('CAGLAYANCERIT',46),
('DULKADIROGLU',46),
('EKINOZU',46),
('ELBISTAN',46),
('GOKSUN',46),
('NURHAK',46),
('ONIKISUBAT',46),
('PAZARCIK',46),
('TURKOGLU',46);

INSERT INTO district(name, city_id) VALUES
('EFLANI',78),
('ESKIPAZAR',78),
('MERKEZ',78),
('OVACIK',78),
('SAFRANBOLU',78),
('YENICE',78);

INSERT INTO district(name, city_id) VALUES
('AYRANCI',70),
('BASYAYLA',70),
('ERMENEK',70),
('KAZIMKARABEKIR',70),
('MERKEZ',70),
('SARIVELILER',70);

INSERT INTO district(name, city_id) VALUES
('AKYAKA',36),
('ARPACAY',36),
('DIGOR',36),
('KAGIZMAN',36),
('MERKEZ',36),
('SARIKAMIS',36),
('SELIM',36),
('SUSUZ',36);

INSERT INTO district(name, city_id) VALUES
('ABANA',37),
('AGLI',37),
('ARAC',37),
('AZDAVAY',37),
('BOZKURT',37),
('CIDE',37),
('CATALZEYTIN',37),
('DADAY',37),
('DEVREKANI',37),
('DOGANYURT',37),
('HANONU',37),
('IHSANGAZI',37),
('INEBOLU',37),
('KURE',37),
('MERKEZ',37),
('PINARBASI',37),
('SEYDILER',37),
('SENPAZAR',37),
('TASKOPRU',37),
('TOSYA',37);

INSERT INTO district(name, city_id) VALUES
('AKKISLA',38),
('BUNYAN',38),
('DEVELI',38),
('FELAHIYE',38),
('HACILAR',38),
('INCESU',38),
('KOCASINAN',38),
('MELIKGAZI',38),
('OZVATAN',38),
('PINARBASI',38),
('SARIOGLAN',38),
('SARIZ',38),
('TALAS',38),
('TOMARZA',38),
('YAHYALI',38),
('YESILHISAR',38);

INSERT INTO district(name, city_id) VALUES
('BAHSILI',71),
('BALISEYH',71),
('CELEBI',71),
('DELICE',71),
('KARAKECILI',71),
('KESKIN',71),
('MERKEZ',71),
('SULAKYURT',71),
('YAHSIHAN',71);

INSERT INTO district(name, city_id) VALUES
('BABAESKI',39),
('DEMIRKOY',39),
('KOFCAZ',39),
('LULEBURGAZ',39),
('MERKEZ',39),
('PEHLIVANKOY',39),
('PINARHISAR',39),
('VIZE',39);

INSERT INTO district(name, city_id) VALUES
('AKCAKENT',40),
('AKPINAR',40),
('BOZTEPE',40),
('CICEKDAGI',40),
('KAMAN',40),
('MERKEZ',40),
('MUCUR',40);

INSERT INTO district(name, city_id) VALUES
('ELBEYLI',79),
('MERKEZ',79),
('MUSABEYLI',79),
('POLATELI',79);

INSERT INTO district(name, city_id) VALUES
('BASISKELE',41),
('CAYIROVA',41),
('DARICA',41),
('DERINCE',41),
('DILOVASI',41),
('GEBZE',41),
('GOLCUK',41),
('IZMIT',41),
('KANDIRA',41),
('KARAMURSEL',41),
('KARTEPE',41),
('KORFEZ',41);

INSERT INTO district(name, city_id) VALUES
('AHIRLI',42),
('AKOREN',42),
('AKSEHIR',42),
('ALTINEKIN',42),
('BEYSEHIR',42),
('BOZKIR',42),
('CIHANBEYLI',42),
('CELTIK',42),
('CUMRA',42),
('DERBENT',42),
('DEREBUCAK',42),
('DOGANHISAR',42),
('EMIRGAZI',42),
('EREGLI',42),
('GUNEYSINIR',42),
('HADIM',42),
('HALKAPINAR',42),
('HUYUK',42),
('ILGIN',42),
('KADINHANI',42),
('KARAPINAR',42),
('KARATAY',42),
('KULU',42),
('MERAM',42),
('SARAYONU',42),
('SELCUKLU',42),
('SEYDISEHIR',42),
('TASKENT',42),
('TUZLUKCU',42),
('YALIHUYUK',42),
('YUNAK',42);

INSERT INTO district(name, city_id) VALUES
('ALTINTAS',43),
('ASLANAPA',43),
('CAVDARHISAR',43),
('DOMANIC',43),
('DUMLUPINAR',43),
('EMET',43),
('GEDIZ',43),
('HISARCIK',43),
('MERKEZ',43),
('PAZARLAR',43),
('SIMAV',43),
('SAPHANE',43),
('TAVSANLI',43);

INSERT INTO district(name, city_id) VALUES
('AKCADAG',44),
('ARAPGIR',44),
('ARGUVAN',44),
('BATTALGAZI',44),
('DARENDE',44),
('DOGANSEHIR',44),
('DOGANYOL',44),
('HEKIMHAN',44),
('KALE',44),
('KULUNCAK',44),
('PUTURGE',44),
('YAZIHAN',44),
('YESILYURT',44);

INSERT INTO district(name, city_id) VALUES
('AHMETLI',45),
('AKHISAR',45),
('ALASEHIR',45),
('DEMIRCI',45),
('GOLMARMARA',45),
('GORDES',45),
('KIRKAGAC',45),
('KOPRUBASI',45),
('KULA',45),
('SALIHLI',45),
('SARIGOL',45),
('SARUHANLI',45),
('SELENDI',45),
('SOMA',45),
('SEHZADELER',45),
('TURGUTLU',45),
('YUNUSEMRE',45);

INSERT INTO district(name, city_id) VALUES
('ARTUKLU',47),
('DARGECIT',47),
('DERIK',47),
('KIZILTEPE',47),
('MAZIDAGI',47),
('MIDYAT',47),
('NUSAYBIN',47),
('OMERLI',47),
('SAVUR',47),
('YESILLI',47);

INSERT INTO district(name, city_id) VALUES
('AKDENIZ',33),
('ANAMUR',33),
('AYDINCIK',33),
('BOZYAZI',33),
('CAMLIYAYLA',33),
('ERDEMLI',33),
('GULNAR',33),
('MEZITLI',33),
('MUT',33),
('SILIFKE',33),
('TARSUS',33),
('TOROSLAR',33),
('YENISEHIR',33);

INSERT INTO district(name, city_id) VALUES
('BODRUM',48),
('DALAMAN',48),
('DATCA',48),
('FETHIYE',48),
('KAVAKLIDERE',48),
('KOYCEGIZ',48),
('MARMARIS',48),
('MENTESE',48),
('MILAS',48),
('ORTACA',48),
('SEYDIKEMER',48),
('ULA',48),
('YATAGAN',48);

INSERT INTO district(name, city_id) VALUES
('BULANIK',49),
('HASKOY',49),
('KORKUT',49),
('MALAZGIRT',49),
('MERKEZ',49),
('VARTO',49);

INSERT INTO district(name, city_id) VALUES
('ACIGOL',50),
('AVANOS',50),
('DERINKUYU',50),
('GULSEHIR',50),
('HACIBEKTAS',50),
('KOZAKLI',50),
('MERKEZ',50),
('URGUP',50);

INSERT INTO district(name, city_id) VALUES
('ALTUNHISAR',51),
('BOR',51),
('CAMARDI',51),
('CIFTLIK',51),
('MERKEZ',51),
('ULUKISLA',51);

INSERT INTO district(name, city_id) VALUES
('AKKUS',52),
('ALTINORDU',52),
('AYBASTI',52),
('CAMAS',52),
('CATALPINAR',52),
('CAYBASI',52),
('FATSA',52),
('GOLKOY',52),
('GULYALI',52),
('GURGENTEPE',52),
('IKIZCE',52),
('KABADUZ',52),
('KABATAS',52),
('KORGAN',52),
('KUMRU',52),
('MESUDIYE',52),
('PERSEMBE',52),
('ULUBEY',52),
('UNYE',52);

INSERT INTO district(name, city_id) VALUES
('BAHCE',80),
('DUZICI',80),
('HASANBEYLI',80),
('KADIRLI',80),
('MERKEZ',80),
('SUMBAS',80),
('TOPRAKKALE',80);

INSERT INTO district(name, city_id) VALUES
('ARDESEN',53),
('CAMLIHEMSIN',53),
('CAYELI',53),
('DEREPAZARI',53),
('FINDIKLI',53),
('GUNEYSU',53),
('HEMSIN',53),
('IKIZDERE',53),
('IYIDERE',53),
('KALKANDERE',53),
('MERKEZ',53),
('PAZAR',53);

INSERT INTO district(name, city_id) VALUES
('ADAPAZARI',54),
('AKYAZI',54),
('ARIFIYE',54),
('ERENLER',54),
('FERIZLI',54),
('GEYVE',54),
('HENDEK',54),
('KARAPURCEK',54),
('KARASU',54),
('KAYNARCA',54),
('KOCAALI',54),
('PAMUKOVA',54),
('SAPANCA',54),
('SERDIVAN',54),
('SOGUTLU',54),
('TARAKLI',54);

INSERT INTO district(name, city_id) VALUES
('19 MAYIS',55),
('ALACAM',55),
('ASARCIK',55),
('ATAKUM',55),
('AYVACIK',55),
('BAFRA',55),
('CANIK',55),
('CARSAMBA',55),
('HAVZA',55),
('ILKADIM',55),
('KAVAK',55),
('LADIK',55),
('SALIPAZARI',55),
('TEKKEKOY',55),
('TERME',55),
('VEZIRKOPRU',55),
('YAKAKENT',55);

INSERT INTO district(name, city_id) VALUES
('BAYKAN',56),
('ERUH',56),
('KURTALAN',56),
('MERKEZ',56),
('PERVARI',56),
('SIRVAN',56),
('TILLO',56);

INSERT INTO district(name, city_id) VALUES
('AYANCIK',57),
('BOYABAT',57),
('DIKMEN',57),
('DURAGAN',57),
('ERFELEK',57),
('GERZE',57),
('MERKEZ',57),
('SARAYDUZU',57),
('TURKELI',57);

INSERT INTO district(name, city_id) VALUES
('AKINCILAR',58),
('ALTINYAYLA',58),
('DIVRIGI',58),
('DOGANSAR',58),
('GEMEREK',58),
('GOLOVA',58),
('GURUN',58),
('HAFIK',58),
('IMRANLI',58),
('KANGAL',58),
('KOYULHISAR',58),
('MERKEZ',58),
('SUSEHRI',58),
('SARKISLA',58),
('ULAS',58),
('YILDIZELI',58),
('ZARA',58);

INSERT INTO district(name, city_id) VALUES
('AKCAKALE',63),
('BIRECIK',63),
('BOZOVA',63),
('CEYLANPINAR',63),
('EYYUBIYE',63),
('HALFETI',63),
('HALILIYE',63),
('HARRAN',63),
('HILVAN',63),
('KARAKOPRU',63),
('SIVEREK',63),
('SURUC',63),
('VIRANSEHIR',63);

INSERT INTO district(name, city_id) VALUES
('BEYTUSSEBAP',73),
('CIZRE',73),
('GUCLUKONAK',73),
('IDIL',73),
('MERKEZ',73),
('SILOPI',73),
('ULUDERE',73);

INSERT INTO district(name, city_id) VALUES
('CERKEZKOY',59),
('CORLU',59),
('ERGENE',59),
('HAYRABOLU',59),
('KAPAKLI',59),
('MALKARA',59),
('MARMARAEREGLISI',59),
('MURATLI',59),
('SARAY',59),
('SULEYMANPASA',59),
('SARKOY',59);

INSERT INTO district(name, city_id) VALUES
('ALMUS',60),
('ARTOVA',60),
('BASCIFTLIK',60),
('ERBAA',60),
('MERKEZ',60),
('NIKSAR',60),
('PAZAR',60),
('RESADIYE',60),
('SULUSARAY',60),
('TURHAL',60),
('YESILYURT',60),
('ZILE',60);

INSERT INTO district(name, city_id) VALUES
('AKCAABAT',61),
('ARAKLI',61),
('ARSIN',61),
('BESIKDUZU',61),
('CARSIBASI',61),
('CAYKARA',61),
('DERNEKPAZARI',61),
('DUZKOY',61),
('HAYRAT',61),
('KOPRUBASI',61),
('MACKA',61),
('OF',61),
('ORTAHISAR',61),
('SURMENE',61),
('SALPAZARI',61),
('TONYA',61),
('VAKFIKEBIR',61),
('YOMRA',61);

INSERT INTO district(name, city_id) VALUES
('CEMISGEZEK',62),
('HOZAT',62),
('MAZGIRT',62),
('MERKEZ',62),
('NAZIMIYE',62),
('OVACIK',62),
('PERTEK',62),
('PULUMUR',62);

INSERT INTO district(name, city_id) VALUES
('BANAZ',64),
('ESME',64),
('KARAHALLI',64),
('MERKEZ',64),
('SIVASLI',64),
('ULUBEY',64);

INSERT INTO district(name, city_id) VALUES
('BAHCESARAY',65),
('BASKALE',65),
('CALDIRAN',65),
('CATAK',65),
('EDREMIT',65),
('ERCIS',65),
('GEVAS',65),
('GURPINAR',65),
('IPEKYOLU',65),
('MURADIYE',65),
('OZALP',65),
('SARAY',65),
('TUSBA',65);

INSERT INTO district(name, city_id) VALUES
('ALTINOVA',77),
('ARMUTLU',77),
('CINARCIK',77),
('CIFTLIKKOY',77),
('MERKEZ',77),
('TERMAL',77);

INSERT INTO district(name, city_id) VALUES
('AKDAGMADENI',66),
('AYDINCIK',66),
('BOGAZLIYAN',66),
('CANDIR',66),
('CAYIRALAN',66),
('CEKEREK',66),
('KADISEHRI',66),
('MERKEZ',66),
('SARAYKENT',66),
('SARIKAYA',66),
('SORGUN',66),
('SEFAATLI',66),
('YENIFAKILI',66),
('YERKOY',66);

INSERT INTO district(name, city_id) VALUES
('ALAPLI',67),
('CAYCUMA',67),
('DEVREK',67),
('EREGLI',67),
('GOKCEBEY',67),
('KILIMLI',67),
('KOZLU',67),
('MERKEZ',67);